### ISSUE TITLE
Profiling pathos threads?

### ISSUE THREAD

**Issue by rkatriel-mdsol** [uqfoundation/pathos#102]
Hi,

I am trying to profile execution in threads using a pathos pool. The Anaconda profiler appears unable to pick up any function calls inside the spawned child processes, so I am only able to see as far as:

9. 	~:0(<method 'acquire' of '_thread.lock' objects>)
8. 	threading.py:263(wait)
7. 	threading.py:533(wait)
6. 	pool.py:598(wait)
5. 	pool.py:601(get)
4. 	... my code ....

[Note: the order of the stack trace numbers is reversed by the GitHub formatter]

After the pool is set up, the work is done using multiple calls to pool.apply_async() and the results are combined.

Am I missing something?

Thanks,
Ron

**Comment by mmckerns** [comment]
Check out: https://github.com/uqfoundation/pathos/blob/master/pathos/profile.py.
If this module doesn't do what you are looking for, please expand on this ticket.  If it does, please close this ticket as resolved.

**Comment by rkatriel-mdsol** [comment]
Thanks, Mike. The GitHub documentation is a bit overwhelming in its complexity. I could use some help with creating a minimally working profiling example as I am getting the following error:

  File "/Anaconda-3.6/anaconda/lib/python3.6/site-packages/pathos/profile.py", line 240
    global profiler
SyntaxError: name 'profiler' is used prior to global declaration

My usage of the multiprocessing package is as follows:

    pool = mp.Pool(processes = num_threads)
    results = [pool.apply_async(process_data_files, args = (data_directory, fsublist, ... , output_metadata)) for fsublist in flist]

The function process_data_files calls additional functions to get the work done.

Thanks,
Ron

**Comment by rkatriel-mdsol** [comment]
Note: I get the above error just by including the import statement

import pathos.profile as pr

This is caused by the following line in pathos/profile.py function disable_profiling()

    global profiler

Could this be a Python 3 issue?

Ron

**Comment by mmckerns** [comment]
It was tested in python 3.2 to python 3.5, and the worst it produces is a `SyntaxWarning`.   However, I just tried it in python 3.6.0, and it produces a `SyntaxError`.  Arg... so, yes, I'll need to patch that.  I should be able to do that early tomorrow.  That's the priority.

Your use of `multiprocess` looks fine... Are you are using `multiprocess`, or `multiprocessing`?   FYI, `pathos.multiprocessing` is just `multiprocess` under the hood with a `pathos` wrapper on it.

I'll post a profiler example here after fixing the `global` issue.

**Comment by rkatriel-mdsol** [comment]
Thanks, Mike. I am using pathos.multiprocessing, that is

import pathos.multiprocessing as mp

Best,
Ron

On March 27, 2017 at 8:54:16 PM, Mike McKerns (notifications@github.com) wrote:

It was tested in python 3.2 to python 3.5, and the worst it produces is a SyntaxWarning. However, I just tried it in python 3.6.0, and it produces a SyntaxError. Arg... so, yes, I'll need to patch that. I should be able to do that early tomorrow. That's the priority.

Your use of multiprocess looks fine... Are you are using multiprocess, or multiprocessing? FYI, pathos.multiprocessing is just multiprocess under the hood with a pathos wrapper on it.

I'll post a profiler example here after fixing the global issue.

**Comment by mmckerns** [comment]
I have applied a patch for 3.6 (68d6f3be1b832d3218cf8f7a4fed1f6e7ac32a72).  It should work for you now. If this module doesn't do what you are looking for, please expand on this ticket. If it does, please close this ticket as resolved.

**Comment by rkatriel-mdsol** [comment]
Thanks, Mike. That fixed the error.

I am still unclear on how to instrument my individual processes for profiling. Specifically, how to translate the examples provided in GitHub (i.e., _work function in conjunction with _uimap) to my case above.

**Comment by mmckerns** [comment]
If you look at the module documentation, `_work` is the target function -- like your `process_data_files`.  The function you want to use to configure the profiling is `pathos.profile.profiled` -- it's a decorator.  I don't use it as a decorator in the documented example, but you can.  The arguments of `profiled` configure how you want to run the profiler.  The decorator decorates a function, where the function you decorate will be profiled. 

So for `work = pr.profiled(**config)(_work)`, the `_work` function will be profiled.  However, for `_uimap = pr.profiled(**config)(pool.imap_unordered)`, the `imap_unordered` function will be profiled in the main thread or process, while whatever you pass in will get profiled will get profiled in their own thread or process.

The above is just to *configure* the profiling.  You have to turn on and off profiling with `enable_profiling` and `disable_profiling`.


There are two examples in the module documentation.  I was describing elements of the first example above, which uses "low-level" functions.  The following is the latter example, self-contained, which uses a "high-level" function.  Here `_test_import` is the target function with one argument (`'pox'` in the example), and `profile` is the decorator which prints the profiling table.

```
    >>> import pathos.profile as pr 
    >>>
    >>> # activate profiling
    >>> pr.enable_profiling()
    >>> 
    >>> # print stats for profile of 'import math' in another process
    >>> def test_import(module):
    ...    __import__(module)
    ...
    >>> import pathos.pools as pp
    >>> pool = pp.ProcessPool(1)
    >>> pr.profile('cumulative', pipe=pool.pipe)(test_import, 'pox')
         10 function calls in 0.003 seconds
   Ordered by: cumulative time
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.003    0.003 <stdin>:1(test_import)
        1    0.002    0.002    0.003    0.003 {__import__}
        1    0.001    0.001    0.001    0.001 __init__.py:8(<module>)
        1    0.000    0.000    0.000    0.000 shutils.py:11(<module>)
        1    0.000    0.000    0.000    0.000 _disk.py:15(<module>)
        1    0.000    0.000    0.000    0.000 {eval}
        1    0.000    0.000    0.000    0.000 utils.py:11(<module>)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 info.py:2(<module>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
    >>> pool.close()
    >>> pool.join()
    >>> pool.clear()
```

With a different configuration, you can have the profiling table written to a file or files.

**Comment by rkatriel-mdsol** [comment]
That helps a bit. However, still a few loose ends in my understanding:

1. Does the pool (pp) replace the current one I am using from the multiprocessing module (mp)? Can I invoke apply_async on this version? 
2. Where/how to I tell the the "pipe" that I would like to profile process_data_files and its called functions in the spawned sub-processes?
3. What is 'pox'? Is that a placeholder for a module name in my code or something related to pathos?

Thanks,
Ron

**Comment by rkatriel-mdsol** [comment]
Thanks, Mike. That helps a lot. The last missing step is how to get from the above to invoking process_data_files in my apply_async "loop". Passing it a "decorated" function does not work, so there must be some way to combine the example you provided with what I am trying to do, i.e.,

results = [pool.apply_async(process_data_files, args = (data_directory, fsublist, ... , output_metadata)) for fsublist in flist]

Appreciate your help with this.

Ron

**Comment by mmckerns** [comment]
What do you mean, "doesn't work"?  Can you post your traceback and a full minimal example?  Note I can't run your code as you haven't provided a minimal example that demonstrates what you are seeing.

If you are saying that you are getting a pickling error on the decorator, then that's one thing... if it's that the interface provided doesn't satisfy your use case, that's another.

Note you have options to apply the decorator, you can apply it to `apply_async` and you can apply it to `process_data_files`.

**Comment by rkatriel-mdsol** [comment]
Here is my profiling code so far (encapsulated the function mapParallel):

    # enable profiling
    pr.enable_profiling()

    # generate a 'profiled' version of process_cde_files
    config = dict(gen=pr.process_id)
    process_cde_files_prof = pr.profiled(**config)(process_cde_files)

    pool = mp.Pool(processes = num_threads)
    results = [pool.apply_async(process_cde_files_prof, args = (data_directory, fsublist, ..., output_metadata)) for fsublist in flist]

    # disable profiling
    pr.disable_profiling()

Here is the output from the profiler:

7. 	~:0(<method 'disable' of '_lsprof.Profiler' objects>)
6. 	profile.py:229(stop_profiling)
5. 	profile.py:236(disable_profiling)
4. 	datamine_keywords_regexSearch_multithreaded.py:238(mapParallel)
3. 	datamine_keywords_regexSearch_multithreaded.py:262(process_cde_directory)
2. 	datamine_keywords_regexSearch_multithreaded.py:291(main)
1. 	datamine_keywords_regexSearch_multithreaded.py:36(<module>)
0. 	~:0(<built-in method builtins.exec>)

**Comment by mmckerns** [comment]
Your code **looks** fine.  I can't try it, as I don't have a minimal example from you.  I can only test against my own code in this case.  I can tell you that I'm not sure if I've tried this all inside a function call, such as `mapParallel`, and also I'm not certain if I've used it inside of a list comprehension.  In your output from the profiler, is that code that is being executed in `main`?  If so, that's probably not what you want.

You might want to try `profile` instead of `profiled` -- the reason being, is that the `enable_profiling` is sent across the `pipe` object for you, instead of having to send it yourself.  What I mean, is make your example look more like the second one at the module level (i.e. the one I posted above).

**Comment by mmckerns** [comment]
I can check my one code against the two cases you are presenting (used in a function, and used in a list comprehension), just to scratch those off, as I don't remember if I've tested that before.  But, try `profile` and configure with the `pipe` keyword.

**Comment by rkatriel-mdsol** [comment]
profile configured with the pipe keywords works (the output has useful profile information):

def mapParallel(flist, data_directory, ... , output_metadata, num_threads):
    # enable profiling
    pr.enable_profiling()

    import pathos.pools as pp
    ppool = pp.ProcessPool(1)
    mpool = mp.Pool(processes = num_threads)

    output = {}
    for fsublist in flist:
        # generate a 'profiled' version of process_data_files
        process_data_files_prof = pr.profile('cumulative', pipe=ppool.pipe)(process_data_files, data_directory, fsublist, ... , output_metadata)
        results = mpool.apply_async(process_data_files_prof)
        output.update(results.get())

    # disable profiling
    pr.disable_profiling()

    return output

However, I get an error when trying to merge the dictionaries returned by apply_async:

  File "datamine_keywords_regexSearch_multithreaded.py", line 253, in mapParallel
    output.update(results.get())

  File "/Anaconda-3.6/anaconda/lib/python3.6/site-packages/multiprocess/pool.py", line 608, in get
    raise self._value

TypeError: 'dict' object is not callable

I will try to figure out the reason tomorrow.

Ron

**Comment by mmckerns** [comment]
Ron, good.  I'm glad it profiles what you want.  So maybe it's not clear from the documentation, but I think you shouldn't have to do `enable_profiling` and `disable_profiling` with `pathos.profile.profile`.  The reason is that it sends those two functions across the pipe with your target function in between.   I think the reason you weren't seeing what you wanted with `pathos.profile.profiled`  is that you didn't pass something through the pipe to `enable_profiling` in the spawned threads.  Like I said, it's probably that the documentation could be clearer on that point.  Your feedback is important to help make the documentation clearer, so thanks for iterating with me on this issue.

I can't help with your TypeError without seeing your code.  All I can say there is that this is how you'd produce that error:
```
>>> d = dict()
>>> d()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'dict' object is not callable
```

If you don't have any further issues with using profiling, then please close this ticket.  If you have comments about the documentation, please leave them here.  If you find a new issue with `pathos`, even if it's related to the above code, then please open a new ticket.

**Comment by rkatriel-mdsol** [comment]
Thanks for the tips. Here is a minimal version of the code that has the profiling work:

    # instrument profiling
    import pathos.pools as pp
    ppool = pp.ProcessPool(1)
    mpool = mp.Pool(processes = num_threads)

    # used a 'profiled' version of process_data_files
    results = [mpool.apply_async(pr.profile('cumulative', pipe=ppool.pipe)(process_data_files, data_directory, fsublist, ... , output_metadata)) for fsublist in flist]

    output = {}
    #for i in range(0, num_threads):
    #    output.update(results[i].get())

    return output

A few closing comments:

1. Assuming this is possible, it might be less confusing for new users if the pool used by the pipe was encapsulated in profile(). Perhaps it could be a default value for the argument.
2. Each thread prints out separate profiling output, even though they call the same functions (with different data). An option to accumulate across all threads would be very nice.
3. The dictionary merging is commented out because the dict error suppresses printout of profiling (the error does not occur with the uninstrumented version of process_data_files). 

Thanks for your help. I will close this ticket.

Best,
Ron

**Comment by mmckerns** [comment]
I appreciate the comments.  I'll open a new ticket with them in it.
