### ISSUE TITLE
profile returns stunted dict

### ISSUE THREAD

**Issue by rkatriel-mdsol** [uqfoundation/pathos#104]
Hi Mike,

The pathos profile function in the profile module returns dictionary values with a get method that is not working (it might be shadowed).

Here is a minimal example demonstrating the issue:

    import pathos.multiprocessing as mp
    import pathos.profile as pr
    import pathos.pools as pp

    BUGGY = True

    ppool = pp.ProcessPool(1)
    mpool = mp.Pool(processes = 2)

    def make_dict(i):
        if i == '0':
            dict = { 'a': 1, 'b': 2 }
        else:
            dict = { 'c': 3, 'd': 4 }
        return dict

    if BUGGY:
        # use a 'profiled' version of make_dict
        results = [mpool.apply_async(pr.profile('cumulative', pipe=ppool.pipe)(make_dict, i)) for i in (0, 1)]
    else:
        # use make_dict directly (no profiling)
        results = [mpool.apply_async(make_dict, args = (str(i))) for i in (0, 1)]

    for i in range(0, 2):
        print(results[i].get())

The code works when BUGGY = False, but fails with the following error when BUGGY = True:

TypeError: 'dict' object is not callable

Thanks,
Ron

**Comment by mmckerns** [comment]
I'm not sure I'm understanding what your intent is... but to me it looks like your code is buggy.

```
if BUGGY:
    # use a 'profiled' version of make_dict
    results = [mpool.apply_async(lambda x:x, (pr.profile('cumulative', pipe=ppool.pipe)(make_dict, str(i)),)) for i in (0, 1)]
else:
    # use make_dict directly (no profiling)
    results = [mpool.apply_async(make_dict, args=(str(i),)) for i in (0, 1)]
```

First, without profiling, you *should* pass an iterable to apply_async as the argument.  It's not always required, but it's the better thing to do.

Second, the profiled version is building two pools... one `ppool` that you are calling `make_dict` in, and another `mpool` that is being used to call `pr.profile`.  I assume that's what you want.  You could just use `ppool.apipe` and not even use the `mpool` to get the same result without involving a second pool.  There's a bug in that you aren't passing in `str(i)` to `make_dict`.  The other bug -- the one you are seeing the error for -- is that `make_dict` returns a `dict`, and thus `pr.profile` returns a `dict`... and thus you are trying to use a `dict` as the first argument of `apply_async`... which expects a function.  I've modified your code to use a passthrough `lambda`, and it works.   My suggestion, if you want asynchronous profiled functions, is to use the asynchronous pipe in the `pipe` argument, and then you shouldn't need the `mpool` at all.

**Comment by rkatriel-mdsol** [comment]
Thanks, Mike. The lambda solution was very helpful!

Regarding utilizing two pools... it does not appear I have a choice. The first (ppool) is needed by the pathos profiler. The second (mpool) spawns multiple threads for concurrent execution. Specifically,

1. ppool does not support apply_async: AttributeError: 'ProcessPool' object has no attribute 'apply_async'

2. As one would expect, mpool does not support pipe: AttributeError: 'Pool' object has no attribute 'pipe'

3. The profile module requires that the pipe provided should come from pool built with nodes=1. So if multiple threads are desired that would not be possible.

Am I missing something?

Thanks,
Ron

**Comment by rkatriel-mdsol** [comment]
Upon further reading and experimenting, I believe that you were suggesting the following:

    results = [ppool.apipe(lambda x:x, (pr.profile('cumulative', pipe=ppool.pipe)(make_dict, str(i)),)) for i in (0, 1)]

Would this spawn multiple asynchronous threads even though the pool has only one node?

**Comment by mmckerns** [comment]
Ron,

So, yes, `pathos.multiprocessing.Pool` uses `apply` and `apply_async`, while `pathos.pools.ProcessPool` uses `pipe` and `apipe`.  They are essentially the same... the code in `pools` is the newer interface.

The code you have just above (with `apipe` and `pipe`), when the pool only has one worker, it will only spawn one process to do all of the work.  Also note you are spawning a **process** not **threads**.  If you want threads, you want `pathos.pools.ThreadPool` (and/or `pathos.threading.Pool`)

And, I meant, this, which is simpler:
`results = [pr.profile('cumulative', pipe=ppool.apipe)(make_dict, str(i)) for i in (0,1)]`,
and it returns a list of asynchronous `ApplyResult` objects. The only issue with it, is as you pointed out, the Pool requires there be only one worker.

So, if you want more than one thread to do the work, yes, you need multiple pools to do what you seem to want to do.

**Comment by rkatriel-mdsol** [comment]
Mike,

Thanks so much for your help! I think I am good now. My next step is to test the pathos profiler under heavy load (12 concurrent  processes) and a large volume of data on my MacPro. I will let you know if I encounter any issues.

Best,
Ron

**Comment by rkatriel-mdsol** [comment]
Mike,

There appears to be a serious bottleneck in the profiling code. Out of 12 concurrent processes only one is at 100% CPU utilization. The rest appear to be idling (very close to 0% CPU utilization).

This does not happen with profiling turned off, but still using the apply_async function of the pathos multiprocessing package. All 12 cores are pegged at 100% (according to the Activity Monitor).

Any thoughts? Could this be due to the pipe associated with the single-node pool?

Ron

**Comment by mmckerns** [comment]
Ron,

Honestly, I don't know the answer to that.   However, it's a very "unusual" use case to profile the code in parallel.  Typically, you profile in another node, and in the same workflow as your code without profiling -- but the intent is to not profile in parallel beyond the `Pool` with one node (which is one reason there's a sharp limitation on the number of processes that the profiling `Pool` can take in `pipe`).  Either I never tried it, or more likely, I put in the limitation on the pool to one process because I tried something similar to what you are and found that profiling doesn't work with more than one process/thread -- but I don't remember.

I would however, caution you to be careful that you are using two different `Pool`.  Typically if you have a hierarchy of `Pool`, you should use one `ThreadPool` and one `ProcessPool`, because `pathos` does some things behind the scenes to reuse pools so it removes the overhead of creating them repeatedly.  What I mean by that is, if you use `pathos.pools.ProcessingPool` and `pathos.multiprocessing.Pool`, you may actually be using the same `Pool` behind the scenes and not know it.  The intent is to use the interface in `pathos.pools`, the other is deprecated.

**Comment by rkatriel-mdsol** [comment]
Appreciate the detailed explanation. Sounds like the software involves a singleton (by design). Would it be possible to work around it by moving the profiling into each of the sub-processes? By the way, I am avoiding using threads because when I tried (using the native Python threading package) it did not utilize all the cores on my machine.

**Comment by mmckerns** [comment]
Ron, in python, all threads will launch on one core.  `ProcessPool` launches processes, and that's multi-core.  What I'm saying is that I typically run a hierarchical map structure, with one `ThreadPool` and one `ProcessPool`.  For example, using multiple threads in an inner `map` function, where an outer `map` function launches each invocation of the former in a new process.  Use threads where you need parallel workflow, but not heaving lifting... and processes for when you need heavier lifting.

As far as working around it... I don't know.  You are welcome to try, and if you discover a good work-around, please feel free to share your solution.

**Comment by rkatriel-mdsol** [comment]
Thanks Mike. I got this to work inside the processes by dropping the "pipe" paradigm and going with a "decorated" function. Here is the relevant code:

def process_data_files_aux (data_directory, filename_list, ..., output_metadata):
    # use a 'profiled' version of process_data_files
    config = dict(gen=pr.process_id)
    process_data_files_profiled = pr.profiled(**config)(process_data_files)
    pr.enable_profiling()
    results = process_data_files_profiled(data_directory, filename_list, case_sensitive, keywords, robj_fast, robj_slow, output_metadata)
    pr.print_stats(sort='cumulative')
    pr.disable_profiling()
    return results

The above function is called as follows:

    pool = mp.Pool(processes = num_threads)
    results = [pool.apply_async(process_data_files_aux, args = (data_directory, fsublist, ... , output_metadata),) for fsublist in flist]

The solution allows concurrent profiling (on 12 cores in my case).

Currently the stats are printed separately for each process. Is there a way to programmatically get the statistics from the processes so that their timing information can be combined into a single report?

Thanks,
Ron

**Comment by mmckerns** [comment]
Ron,

Yep, that works.  Looks like you have the hang of the module now.

So... can you roll all the stats together?  I'm pretty sure the answer is no.  You can pipe them to the same file, but that's going to give you 12 tables printed to one file.

**Comment by rkatriel-mdsol** [comment]
There may be a way to combine the stats after all. Profiler dumps can be read into memory as follows

    import marshal

    fobj = open('/Users/.../id-60459.prof', 'rb')

    stats = marshal.load(fobj)

The stats variable contains a Python dictionary with the profiling information, such as 

    {('/Anaconda-3.6/anaconda/lib/python3.6/codecs.py', 185, '__init__'): (1,
      1,
      1.2e-05,
      1.2e-05,
      {('~', 0, '<built-in method io.open>'): (1, 1, 1.2e-05, 1.2e-05)}),
    ...
    }

See https://zameermanji.com/blog/2012/6/30/undocumented-cprofile-features/ for details.

Ron
