### ISSUE TITLE
new pool instance won't run because a previous pool instance was closed

### ISSUE THREAD

**Issue by FilipMiscevic** [uqfoundation/pathos#111]
If I run a Pool as follows,

    pool = Pool()

    data = pool.map(foo, bar)

    pool.close()
    pool.join()

then try to run the very same code again, I get an assertion error stating that the Pool's state is not 'RUN', e.g. it is closed. Forcing the pool to restart works.

Is Pool deliberately implemented as a singleton? Otherwise, this strikes me as unintuitive behavior. 

Perusing the multiprocessing.py file, I also see:

#FIXME: probably not good enough... should store each instance with a uid
__STATE = _ProcessPool__STATE = {}

**Comment by mmckerns** [comment]
Yes, `pathos` is built in such a way that if a pool is created with identical state as the prior pool, it will not create a new pool.  So, that is the intended behavior, and why there is a `restart`.  I plan to, in the future, also make the pool register by uid, so it's possible to further refine this behavior.  Does that answer your question?

**Comment by FilipMiscevic** [comment]
Thanks for clarifying.

**Comment by lukeolson13** [comment]
Can you elaborate on how restart should be used? I tried a plethora of combinations of restarting the pool, to no avail. The only thing that has kept my code from causing this error every time I run it is to pass nodes=<some int> into Pool().

**Comment by mmckerns** [comment]
@lukeolson13: `pathos` persists it's pools in an internal registry... so that if you create a pool that is "the same" as a previous pool (i.e. same number of nodes, same other configuration parameters), it reuses the old one instead of creating a new pool instance.  Hence, you either have to `restart` an old pool instance that has been "closed", or you have to "delete" the old instance from the registry.

```
>>> square = lambda x:x*x
>>> 
>>> import pathos.pools as pp
>>> pool = pp.ProcessPool()
>>> pool.map(square, range(4))
[0, 1, 4, 9]
>>> pool.close()
>>> pool.join()
>>> 
>>> # we still have the old closed pool instance... so it should fail
>>> pool = pp.ProcessPool()
>>> pool.map(square, range(4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/pathos-0.2.2.dev0-py2.7.egg/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/Users/mmckerns/lib/python2.7/site-packages/multiprocess-0.70.6.dev0-py2.7-macosx-10.12-x86_64.egg/multiprocess/pool.py", line 250, in map
    assert self._state == RUN
AssertionError
>>> 
>>> # let's restart the pool
>>> pool.restart()
<multiprocess.pool.Pool object at 0x10e185f50>
>>> pool.map(square, range(4))
[0, 1, 4, 9]
>>> # the other option is to remove the old pool instance
>>> pool.close()
>>> pool.join() 
>>> pool.clear()
>>> 
>>> pool = pp.ProcessPool()
>>> pool.map(square, range(4))
[0, 1, 4, 9]
>>> pool.close()
>>> pool.join()
>>> pool.clear()
>>>
```

**Comment by mmckerns** [comment]
by changing the number of nodes when you create the pool, you essentially are signaling you want a new pool, and don't want to reuse the old pool instance.

**Comment by lukeolson13** [comment]
@mmckerns how to do you re-access those pools once you've garbage collected your `pool` variable? Basically I'm running into the issue where the pool is persisting (and thus taking up needed memory) and I'd like to clear it later on in the script (and am unable to clear it at time of use). I just tried looking it up in the registry using `hosts.get_profiles()`, but nothing is showing.

**Comment by mmckerns** [comment]
```
>>> import pathos.multiprocessing as mp
>>> import pathos.pools as pp
>>> mp.__STATE
{}
>>> p = pp.ProcessPool()
>>> p.map(lambda x:x*x, [1,2,3,4])
[1, 4, 9, 16]
>>> mp.__STATE
{'pool': <multiprocess.pool.Pool object at 0x10dee8450>}
>>> p.close()
>>> p.join()
>>> mp.__STATE
{'pool': <multiprocess.pool.Pool object at 0x10dee8450>}
>>> p.clear()
>>> mp.__STATE
{}
>>> 
```

**Comment by gcambray** [comment]
Hi @mmckerns
I seem to having the same problem as the OP but with pathos.pools._ProcessPool (I need the chunksize arguments!)
I have tried to do what is discussed above, but _ProcessPool do not have restart() or clear() methods.
Changing the number of process at the second iteration of the for loop does not work either, so maybe it is a different issue entirely. Any suggestions?
Happy to provide more details as needed. Thanks!
