### ISSUE TITLE
What is the difference between ParallelPool and ProcessingPool?

### ISSUE THREAD

**Issue by LifeWorks** [uqfoundation/pathos#115]
I have no idea what are the difference, so don't know what I should use.

If anyone can explain a bit, it will be appreciated. Thanks.

**Comment by mmckerns** [comment]
The difference is that `ProcessingPool` uses `multiprocess` and `ParallelPool` uses `ppft`.  The former is for process-parallel computing, while the latter can be used across a network connection.  Typically, use `ProcessingPool`, unless you need to do distributed computing.  Also, they serialize differently... `multiprocess` uses `dill` (pickling), while `ppft` uses `dill.source` (extracting the source code).
