### ISSUE TITLE
Usage of Pathos

### ISSUE THREAD

**Issue by AlexandreMPDias** [uqfoundation/pathos#135]
On the first line of #About Pathos it says 

> The goal of pathos is to enable the user to extend their own code to parallel and distributed computing with minimal refactoring.

So I was running multiprocessing on Windows and it raised some errors with Pickle. In an attempt to avoid it, I searched for another multiprocessing lib, and I stumbled upon Pathos... So I went looking on the documentation for what I would need to change on my program.

I have this class here:

```py
from multiprocessing import Process

class Klass(Process, Broadcaster, Listener):
    def __init__(self):
        Process.__init__(self)
        Broadcaster.__init__(self)
        Listener.__init__(self)

    def run(self):
        #do stuff

a = Klass()
b = Klass()
a.add_listener(b)
a.start()
b.start()
```

I searched, but I couldnt find any class that would create Processes and run them in parallel with minimal refactoring of the code above... I could only do it by redoing the entire code :/

Any suggestion?

**Comment by mmckerns** [comment]
It's there, just not obvious...  `pathos` is intended to be a higher level interface to `pools`, and it leverages several packages to do so.  For the `Process` class, you are interested in `multiprocess`.

```
>>> import pathos
>>> pathos.helpers.mp.Process
<class 'multiprocess.process.Process'>
>>> import multiprocess
>>> multiprocess.Process
<class 'multiprocess.process.Process'>
```

Please reopen this issue if my response isn't sufficient.
