### ISSUE TITLE
"chunksize" argument not passed on

### ISSUE THREAD

**Issue by BeWe11** [uqfoundation/pathos#152]
Hey,

the standard `map` method of the  `multiprocessing.Pool` class has a `chunksize` parameter. This parameter is very important to me, because my calculations don't take a lot of time too complete.

As of now, the `map` method (and all other methods) of the `pathos.pools.ProcessPool` class does not pass this parameter to the `pathos.multiprocessing.Pool` class. In fact, it passes no keyword arguments at all.

The ProcessPool.map method returns
```python
return _pool.map(star(f), zip(*args)) # chunksize
```
There even is a commend `# chunksize`, maybe it's a TODO reminder? The chunksize is easily passed on if the keyword arguments are passed like this:

```python
return _pool.map(star(f), zip(*args), **kwds) # chunksize
```

Is there any reason why these parameters are not passed on, especially since there is even a commend indicating that someone thought about the chunksize parameter?

Thank you!

**Comment by mmckerns** [comment]
There's a reason it's not used, yes.  If you want the exact same interface as `multiprocessing` provides, use `pathos.pools._ProcessPool`.   Close this ticket if the answer is sufficient for your needs.

**Comment by BeWe11** [comment]
Thank you for your answer. Although I'm still curious as to what this reason is, this fixes my issue. Thanks!
