### ISSUE TITLE
multiprocessing logging?

### ISSUE THREAD

**Issue by forkozi** [uqfoundation/pathos#164]
First, very awesome package.  I'm new to programming, but have been able to implement pathos for a basic multiprocess use-case to speed things up tremendously.  Second, I'm wondering if there's a built-in way to log messages from various processes to a single file.  I see there's a logger() function that returns a "configured logger instance," but newbie me isn't sure what to do with that.  Are there examples out there that demonstrate how to use it?  Thanks so much!

**Comment by aleksejs-fomins** [comment]
Here's how far I got
https://stackoverflow.com/questions/57978518/how-to-do-logging-using-multiprocessing-in-pathos-correctly

**Comment by mmckerns** [comment]
The answer to the above SO question is reasonable: https://stackoverflow.com/a/58142150/2379433.  Closing.  Reopen if the given answer is insufficient for your needs.
