### ISSUE TITLE
How to run non-deamon pool

### ISSUE THREAD

**Issue by Borda** [uqfoundation/pathos#169]
Hello, I am wondering if there is an option how to run non-daemon processing pool within `pathos`. My goal is to run a processing pool within another processing work. I have found a couple of tricks for standard `multiprocessing` package but none of them works for `pathos`...

* https://stackoverflow.com/a/8963618/4521646
* http://mindcache.me/2015/08/09/python-multiprocessing-module-daemonic-processes-are-not-allowed-to-have-children.html

```
from pathos.helpers import mp
class NoDaemonProcess(mp.Process):
    # make 'daemon' attribute always return False
    def _get_daemon(self):
        return False
    def _set_daemon(self, value):
        pass
    daemon = property(_get_daemon, _set_daemon)

from pathos.multiprocessing import ProcessPool
class NoDaemonProcessPool(ProcessPool):
    Process = NoDaemonProcess
```

 where instead of `multiprocessing.pool.Pool` I am using `pathos.multiprocessing.ProcessPool` and the error message is

```
  File ".../experiments.py", line 390, in iterate_map_parallel
    for out in mapping(wrap_func, iterate_vals):
  File "/home/jb/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 735, in next
    raise value
AssertionError: daemonic processes are not allowed to have children
```

**Comment by mmckerns** [comment]
Sorry for the slow response.  `pathos` pools are wrappers around `multiprocess` pools.  Have you tried using `pathos.multiprocessing.Pool`?  That's the raw `multiprocess.Pool` object without the `pathos` wrapper.

**Comment by Borda** [comment]
I played with it for a while and I believe that I tried this too, but it ended the same... :(

**Comment by mmckerns** [comment]
I tried your code, both using `ProcessPool` and `Pool` from `pathos.multiprocessing` and I don't receive an error.

```
from pathos.helpers import mp
class NoDaemonProcess(mp.Process):
    # make 'daemon' attribute always return False
    def _get_daemon(self):
        return False
    def _set_daemon(self, value):
        pass
    daemon = property(_get_daemon, _set_daemon)

from pathos.multiprocessing import ProcessPool
class NoDaemonProcessPool(ProcessPool):
    Process = NoDaemonProcess


if __name__ == '__main__':
    p = NoDaemonProcessPool()
    x = ProcessPool().map(lambda x:x, p.map(lambda x:x, range(4)))
    print(x)
```

Is this not what you intended to do?
It works for me in all versions of python I have, using the most recent development versions of `dill`, `multiprocess`, and `pathos`.

**Comment by mmckerns** [comment]
Also works in the interpreter (only tested 2.7, as opposed to all versions above)
```
Python 2.7.16 (default, Apr  1 2019, 14:50:56) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathos.helpers import mp
>>> class NoDaemonProcess(mp.Process):
...     # make 'daemon' attribute always return False
...     def _get_daemon(self):
...         return False
...     def _set_daemon(self, value):
...         pass
...     daemon = property(_get_daemon, _set_daemon)
... 
>>> from pathos.multiprocessing import ProcessPool
>>> class NoDaemonProcessPool(ProcessPool):
...     Process = NoDaemonProcess
... 
>>> p = NoDaemonProcessPool()
>>> ProcessPool().map(lambda x:x, p.map(lambda x:x, range(4)))
[0, 1, 2, 3]
>>> 
```

**Comment by Borda** [comment]
I got to test it just now and it seems to be working, thanks :)

**Comment by Borda** [comment]
it seems that you examples run fine, but somehow it crashes in my code even I copy the two classes...

**Comment by Borda** [comment]
it runs locally fine but executing your examples on CI it fails for both py2 and py3
https://circleci.com/gh/Borda/BIRL/1417
https://circleci.com/gh/Borda/BIRL/1418

**Comment by mmckerns** [comment]
@Borda: Not sure what's going on with your tests... but the failures in the two links above are potentially due to other issues...

1417: ```UNEXPECTED EXCEPTION: TypeError("cannot serialize '_io.FileIO' object",)```
1418: ```UNEXPECTED EXCEPTION: TypeError("'NoneType' object is not callable",)```
