### ISSUE TITLE
PKG-INFO not available in package version 0.2.4

### ISSUE THREAD

**Issue by casabre** [uqfoundation/pathos#176]
The latest version 0.2.4 does not provide the PKG-INFO metadata according to [PEP314](https://www.python.org/dev/peps/pep-0314/#including-metadata-in-packages). Thus, mirroring to and installing the package from internal Artifactory pypi servers does not work properly because the metadata are missing.

**Comment by mmckerns** [comment]
@casabre: Thanks for that catch.  It's actually included in the release -- autogenerated and matching the specifications detailed in PEP314, with one exception... it's not produced in the top-level directory, it gets placed in the auto-generated directory `pathos.egg.info` at `pathos.egg.info/PKG-INFO`.  The release won't be accepted on `pypi` without this autogenerated file.  I'm not sure why it's located in that directory, but if I need to move/copy it to the top-level directory as part of the release process, then I'll add that to the process.  Note, this is still the case in release `0.2.5`... so I'll see about tweaking the build process to put `PKG-INFO` into the top-level.  Basically, I run this script, and then upload with twine.

```
        cd pathos-0.2.5; python setup.py sdist --format=zip; cd ..
        cd pathos-0.2.5; cd dist; mv -f pathos-0.2.5*zip ..; cd ..; cd ..
        cd pathos-0.2.5; mv -f pathos-0.2.5*zip ..; cd ..

        tar -cvzf pathos-0.2.5.tar.gz pathos-0.2.5
```

**Comment by mmckerns** [comment]
I did a quick search on `python.org` and noticed that I don't see the requirement to put `PGK-INFO` at the top level in the tutorials or pretty much anywhere... just in the one line in `PEP314`.  Regardless, it's an easy fix to copy that file in my release process, so I'll do that.

**Comment by casabre** [comment]
@mmckerns Thank you for the update and the upcoming fix 👍

**Comment by mmckerns** [comment]
Reopening until change is made.

**Comment by mmckerns** [comment]
closing
