### ISSUE TITLE
Logging does not seem to work the same way as in multiprocessing

### ISSUE THREAD

**Issue by aleksejs-fomins** [uqfoundation/pathos#177]
Would you be so kind to help. I am trying hard to get logging to work, and I think I have managed to get it done with multiprocessing, but when I try to do parallel logging in Pathos the same way, it refuses to change properties inbetween different runs

Detailed description of the problem here:
https://stackoverflow.com/questions/57978518/how-to-do-logging-using-multiprocessing-in-pathos-correctly

**Comment by mmckerns** [comment]
Duplicate of #164
