### ISSUE TITLE
Is there any chunksize-like option from built-in processing module?

### ISSUE THREAD

**Issue by hyungjunk** [uqfoundation/pathos#183]
Hi, I don't know if should be posted on issue.

I stumbled on pickling problem of built-in multiprocessing module, so I bypassed using pathos module which works fine with serialize/deserialize.

But I can't find option like `chunksize` in `map` method as it is in built-in multiprocessing module.

Is there any similar option like this?

**Comment by mmckerns** [comment]
Yes.  If you use the `pathos.pools` that begin with an underscore (e.g. `_ProcessPool`, they have the traditional `multiprocessing.Pool` interface (i.e. have `chunksize`).  You can also directly use the `multiprocess` package (which `pathos` is built on), and the `Pool` there has an interface identical to `multiprocessing`.  All pools use `dill` serialization.

Reopen this issue if this doesn't answer your question.
