### ISSUE TITLE
Implementation with tqdm to show overall progress?

### ISSUE THREAD

**Issue by havardl** [uqfoundation/pathos#187]
Are there any examples on how we can use `tqdm` in combination with pathos ThreadPool to show the overall progress of multiple threads?

**Comment by gerhardamegg** [comment]
I recommend checking out [p_tqdm](https://github.com/swansonk14/p_tqdm), a wrapper around pathos.multiprocessing and tqdm.
It's working pretty good

**Comment by mmckerns** [comment]
Thanks @gerhardamegg for the link.
