### ISSUE TITLE
when run the following code in anaconda prompt its going into a infinite loop.how can i fix it?

### ISSUE THREAD

**Issue by chaitu01** [uqfoundation/pathos#194]
```
import multiprocessing as mp
from pathos.multiprocessing import ProcessingPool as Pool
class c():
    def x(self):
        global r
        def r(y):
            return y
        pool = Pool().map
        n=pool(r, [2,2,3,45])
        print(n)
z=c()
z.x()
```

**Comment by mmckerns** [comment]
I'm unable to reproduce an "infinite loop" on any versions of python and pathos, using current dependencies, on MacOS or linux.  I didn't test windows.  I tested in both in a file run from the condo prompt and in a python interpreter session.

Sorry for the long time with no reply.  Please reopen if you are still having an issue.
