### ISSUE TITLE
Is there a multiprocessing Logger for pathos?

### ISSUE THREAD

**Issue by jerrysjin** [uqfoundation/pathos#201]
Is a multiprocessing logger for pathos?

I want to create a MP logger exporting logs to stdout and a single log file which can be passed to every created process. Is it possible to achieve this?

I tried several implementations found on the internet, but no one worked for me.

**Comment by visrra** [comment]
Try using pathos.helpers.mp instead of pathos.multiprocessing.ProcessPool. Reference: https://github.com/uqfoundation/pathos/issues/80#issuecomment-200420713

**Comment by mmckerns** [comment]
@visrra: thanks for the answer.

**Comment by jerrysjin** [comment]
Thanks for your reply! may i ask if there is an example showing the usage? still feel confusing about how to write to file and stdout
