### ISSUE TITLE
ProcessPool vs pathos.helpers.mp.Pool

### ISSUE THREAD

**Issue by visrra** [uqfoundation/pathos#204]
Are there any advantages of ProcessPool compared to pathos.helpers.mp.Pool? The latter seems to be able to handle lambda functions, and it can also display logging outputs of tasks.

**Comment by mmckerns** [comment]
There are several differences, but underneath they are the same. `pathos.pools.ProcessPool` is built on top of `pathos.pools._ProcessPool` (same object as in `pathos.helpers`).  The latter exactly replicates the `multiprocessing` interface, while the former conforms to an interface that is uniform across several backends.  The `ProcessPool` can take several `*args`, is globally cached, and can be reopened once closed. The`_ProcessPool` gives you whatever `multiprocess.Pool` provides.  Both cases can handle lambda functions, and should provide exactly the same level of serialization.

**Comment by visrra** [comment]
Thanks @mmckerns
