### ISSUE TITLE
Exclude local computer from pool

### ISSUE THREAD

**Issue by MarcelRobitaille** [uqfoundation/pathos#226]
Is there any way to exclude the local computer from the pool? Sorry if I'm missing something obvious, but I really can't see a way to do this. I'm trying to use a pool of remote servers and I *never* want my local computer to be used in the pool. This was also very confusing to me, because it wasn't obvious at first.

**Comment by mmckerns** [comment]
From the docs on server configuration (in `__init__`):
```
           ncpus - the number of worker processes to start on the local \
                   computer, if parameter is omitted it will be set to \
                   the number of processors in the system
```
So, I believe, `ncpus = 0` will use no local workers.

**Comment by MarcelRobitaille** [comment]
Thank you. Not sure how I missed "local"
