### ISSUE TITLE
Speeding up dill

### ISSUE THREAD

**Issue by mattiasmar** [uqfoundation/pathos#248]
Hello,
I believe the serialization of dill is the bottleneck in my solution. Is there a way to control dill's parameters through pathos (dill.settings)?
Thanks!

**Comment by mmckerns** [comment]
If you import `dill` and change the settings with `dill.settings`, it should also impact how `pathos` serializes objects.  So, yes, just modify `dill.settings`.  Reopen this if your question is not answered.
