### ISSUE TITLE
host release-specific docs so docs match what's available

### ISSUE THREAD

**Issue by bacook17** [uqfoundation/pathos#264]
The latest version of pathos that is released is 0.3.0, but there are many new commits in master (and therefore the live documentation) that are incorrect because there have been no releases

Just as one example: the documentation says that keyword arguments such as maxtasksperchild will be passed down to the processpool, but this is not actually done in 0.3.0

https://pathos.readthedocs.io/en/latest/pathos.html#pathos.multiprocessing.ProcessPool

**Comment by mmckerns** [comment]
the more appropriate thing to do is to also host docs for each release.  However, a release is imminent.  Reopen if you don't think that is a reasonable path forward and want to continue the discussion.

**Comment by mmckerns** [comment]
reopening. marker to host release docs

**Comment by mmckerns** [comment]
as of the current release (0.3.2), `pathos` now distributes 'latest' and 'stable' docs.  Closing this.
