### ISSUE TITLE
python multiprocessing pathos - AuthenticationError: digest sent was rejected - Windows

### ISSUE THREAD

**Issue by abarik1981** [uqfoundation/pathos#37]
Kindly help...

I have this simply script that runs on Linux (Ubuntu) without any problem, but gives AuthenticationError: digest sent was rejected on Windows and i know its something to do with multiprocessing.Manager, but don't know how to fix it yet:

Here is more details: http://stackoverflow.com/questions/26600561/python-multiprocessing-pathos-authenticationerror-digest-sent-was-rejected

**Comment by mmckerns** [comment]
This may be fixed due to #53.  I will be getting a windows install up and trying it out soon, but feel free to update and check. (Note you'll need to uninstall `processing`).

**Comment by mmckerns** [comment]
Make sure you use `multiprocess.Manager` to match your pools from `pathos`. (i.e. don't use `multiprocessing`, use the fork for everything).

**Comment by fedorzh** [comment]
I went through the issues, but not sure - what would you recommend for fixing this? I have just installed pythos, and getting this error

**Comment by NewBieCoderXD** [comment]
@fedorzh have you tried
`
from pathos.helpers import mp as multiprocess

if __name__ == '__main__':
  manager = multiprocess.Manager()
  ...
`
