### ISSUE TITLE
no close wait or join found for ProcessingPool

### ISSUE THREAD

**Issue by abarik1981** [uqfoundation/pathos#46]
I would like to know why there isn't any pool.close(); pool.join() methods? Are they missing

**Comment by mmckerns** [comment]
Issue part 1:
`close` and `join` should be added, also possibly `terminate`.  I also see an issue here, and probably why I didn't have `close` in the first place… I hold onto the `pool` and reuse it for any new requests of a `pool` -- in theory, that's faster.  However, I **should** let a new `pool` be created, and the old one be destroyed.  I should probably add a new method (`destroy`?) to delete the old `pool`, and maybe also a keyword for `Pool.__init__`, that would force deletion of the old instance and replace it with a new instance.

Issue part 2:
`pathos.pp` should also get similar methods, so the API is consistent.  `pp` uses `destroy`, which is similar to `join` or `close`… but I'll have to look into that further for more details.  It'd be nice to deliver the same functionality for `pathos.pp` as well.

Current workaround… and soon to be implementation…
```
>>> import pathos
>>> p = pathos.multiprocessing.ProcessingPool()
>>> p.map(lambda x:x*x, range(4))
[0, 1, 4, 9]
>>> s = pathos.multiprocessing.__STATE['pool']
>>> s.close()
>>> s.join()
>>> pathos.multiprocessing.__STATE['pool'] = None
```

**Comment by mmckerns** [comment]
`multiprocessing`:

  * `close`: puts `None` on task `Queue` thus signaling "end of queue"
  * `join`: calls `join` on the `task_handler`, `results_handler`, and all `Process` instances in the pool
  * `terminate` calls `close`, then `terminate` on all `Process` instances in the pool, then `join`

Note that pool is just a bunch of `Process` instances with the same input and output queues.
```
        self._pool = [
            Process(target=worker, args=(self._inqueue, self._outqueue,
                                         initializer, initargs))
            for i in range(processes)
            ]
```
And the results and task handlers are just threads that share the above queues.
```
        self._task_handler = threading.Thread(
            target=Pool._handleTasks,
            args=(self._taskqueue, self._inqueue, self._outqueue, self._pool)
            )
        self._task_handler.setDaemon(True)
        self._task_handler._state = RUN
        self._task_handler.start()

        self._result_handler = threading.Thread(
            target=Pool._handleResults,
            args=(self._outqueue, self._cache)
            )
        self._result_handler.setDaemon(True)
        self._result_handler._state = RUN
        self._result_handler.start()
```

Note: good to remember these are `__init__` for `Process` (esp. identity):
```
        self._identity = _current_process._identity + (counter,)
        self._authkey = _current_process._authkey
        self._daemonic = _current_process._daemonic
        self._parent_pid = os.getpid()
        self._popen = None
        self._exiting = False
        self._target = target
        self._args = tuple(args)
        self._kwargs = kwargs.copy()
        self._name = name or 'Process-' + ':'.join(map(str, self._identity))
```

Process `terminate` just sends `SIGTERM`.
```
        '''
        Terminate process; sends `SIGTERM` signal or uses `TerminateProcess()`
        '''
        self._popen.terminate()
```

While `join` waits until the child process terminates.
```
        assert self._parent_pid == os.getpid(), 'can only join a child process'
        assert self._popen is not None, 'can only join a started process'
        if timeout == 0:
            res = self._popen.poll()
        elif timeout is None:
            res = self._popen.wait()
        else:
            res = self._popen.waitTimeout(timeout)
        if res is not None:
            _current_process._children.discard(self)
```

Now need the `pp` equivalent…

**Comment by mmckerns** [comment]
Will open a new ticket to deal with providing a `name` (unique id) for each pool, and being able to remove named `pool` instances from the stored `pool` registry.

**Comment by mmckerns** [comment]
`_serve` and `_clear` methods provided, as noted in #57

**Comment by mmckerns** [comment]
pools now don't receive a unique `_id` by default, but an `_id` can be set.  Making `close`, `join`, and `terminate` work smoothly will probably require adding the automated selection of a unique id.

**Comment by mmckerns** [comment]
added in f434b70197946839749f55021de2f44aa487d174

I ended up leaving the "easy" setting of unique `id` to a later ticket.
There may be some issues when reconfiguring an existing `Pool` (e.g. changing nodes), but that remains to be seen.
