### ISSUE TITLE
Can't pickling problem persists 

### ISSUE THREAD

**Issue by erogol** [uqfoundation/pathos#55]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/processing/pool.py", line 207, in _handleTasks
    put(task)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

I used ProcessingPool. I guess it uses dill by default but still this pickling error persist and I don't figure it out why.  I copies my whole code here (http://pastebin.com/kiUpgzYB) if you like to look. 

This code works perfectly fine with single process which is what I do presently.

**Comment by mmckerns** [comment]
This is most likely purely a pickling problem.  To confirm this, you should try: `f = dill.loads(dill.dumps(_extract_random_patch))`.  If this fails, it's a pickling problem.

If it's a pickling problem, the two easiest ways to help yourself get past a pickling issue are: (1) make sure that you include all the import statements **inside** the function call, or (2) import the function you want to `map` from a separate file.  Paste in the results, and we'll go from there.

**Comment by erogol** [comment]
By the way mapped function is called from a separate file even I appended the main call to same pastebin page. Beside, I will try the others and give you an alert

**Comment by erogol** [comment]
I tried the dill stuff you suggested but did not raised an error.

**Comment by mmckerns** [comment]
…well, if you are not seeing a pickling issue, then the next step is to distill the error.  What will help here is if you can see if you can replicate the error using just a few lines of code.  I don't have a bunch of the packages you are working with, and if it's a problem coming from one of those packages, then it's not really a `pathos` problem, per se.  If you can strip down the problem to a very simple test case that still produces the error… then we can see if it's a much more generally applicable issue.  If it is a general issue, it should be handled here… and if not, we should punt this over to StackOverflow.  If you can distill the error, it makes it much easier to make a clear and quick diagnosis.

**Comment by mmckerns** [comment]
Is any follow-up here still needed/relevant?

**Comment by mmckerns** [comment]
Looking at your pastebin… it still doesn't reflect the suggestions that I had in (1) and (2) above.  If you put `_extract_random_patch` in another file, and then import it inside the `extract_random_patches` function, it gives you a better chance at it pickling and thus working in the `map`.  Another thing that you might want to try is to build the `ProcessingPool` outside of the `extract_random_patch` function and call the `map` inside that function.

I'm going to close this, as it seems to be a very specialized issue and not a generalized one.  If you can show this is a more general issue, please follow-up.
