### ISSUE TITLE
enable pool to have unique id (name) and to be easily deleted from saved pools.

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/pathos#57]
I hold onto the pool and reuse it for any new requests of a pool -- in theory, that's faster. However, I should let a new pool be created, and the old one be destroyed. I should probably add a new method (destroy?) to delete the old pool, and maybe also a keyword for `Pool.__init__`, that would force deletion of the old instance and replace it with a new instance.

**Comment by imazor** [comment]
Hi,

Indeed will be really great if you can add close (or terminate) methods for pool.

**Comment by mmckerns** [comment]
Yes, this is an obvious need -- and will be addressed as soon as I can dedicate some time to it.

**Comment by mmckerns** [comment]
In addition to a `_name` (or `_state` or `_id`), should add a  `register` and `unregister` (or `cache` and `release`) to remove from the `__STATE` registry. The `name` could be a unique id, or a unique int or string that is built from the pool's state (i.e. what would be needed to serialize a pool with `__reduce__`).  Also see #46.

**Comment by mmckerns** [comment]
This is mostly handled by the `_serve` and `_clear` methods, but should be generalized to allow differently named pools.

**Comment by mmckerns** [comment]
This now works with `_id`, `_serve` and `_clear`, however the `_id` is fixed to always be the same in the pool's `__init__`.   I'll leave the automated/manual selection of a unique `_id` in `__init__` to ticket #46.
