### ISSUE TITLE
Pools are less functional on Windows

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/pathos#65]
See https://github.com/uqfoundation/multiprocess/issues/6

A in the interpreter, a workaround is to use:
`dill.settings['recurse'] = True`
which seems to have some good success, 
however, a better and more general approach is
to make sure the target function is fully self-encapsulated
(i.e. doesn't require look-ups outside it's own scope):

```
def slow(x):
    import time
    time.sleep(0.2)
    return x**2 - x
```

and not

```
import time
def slow(x):
    time.sleep(0.2)
    return x**2 - x
```

**Comment by mmckerns** [comment]
They also seem to require 
```
if __name__ == `__main__`:
    from multiprocess import freeze_support
    freeze_support()
```
when run from a file as a script (from the console prompt).

**Comment by ResourceHog** [comment]
Is there an update on this bug?

**Comment by mmckerns** [comment]
@ResourceHog: not yet, but currently It's on my short-list of TODOs.

**Comment by thismygithubusername** [comment]
+1 for this bug to be solved

**Comment by mmckerns** [comment]
I believe this is fixed by https://github.com/uqfoundation/dill/pull/363
