### ISSUE TITLE
Cannot install pathos with easy_install

### ISSUE THREAD

**Issue by vgiotsas** [uqfoundation/pathos#70]
easy_install cannot find the installation package (404 error), this is the output:

```
$ sudo easy_install -f . pathos
Searching for pathos
Reading http://pypi.python.org/simple/pathos/
Best match: pathos 0.1a1
Downloading http://dev.danse.us/packages/pathos-0.1a1.tgz
error: Can't download http://dev.danse.us/packages/pathos-0.1a1.tgz: 404 Not Found
```

Is there any way to manually obtain pathos-0.1a1.tgz?

**Comment by mmckerns** [comment]
The resource `http://dev.danse.us/packages` is temporarily down.  However, the version of `pathos` found there is several years old, and out of date -- you should instead use the version on `github`: https://github.com/uqfoundation/pathos/archive/master.zip

**Comment by mmckerns** [comment]
FYI: the resource is finally back online.
