### ISSUE TITLE
Installation issue for multiprocess

### ISSUE THREAD

**Issue by ritviksahajpal** [uqfoundation/pathos#73]
I used Anaconda python 2.7 (64 bit) to  compile the pathos multiprocess fork. The code is from here: https://github.com/uqfoundation/multiprocess

However getting this error:

>> python.exe C:\Users\ritvik\Downloads\multiprocess-0.70.1\multiprocess-0.70.1\setup.py build

 
running build
running build_ext
building '_multiprocessing' extension
C:\Users\ritvik\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ipy2.7/Modules/_multiprocessing -IC:\Anaconda64\include -IC:\Anaconda64\PC /Tcpy2.7/Modules/_multiprocessing/multiprocessing.c /Fobuild\temp.win-amd64-2.7\Release\py2.7/Modules/_multiprocessing/multiprocessing.obj
multiprocessing.c
c1 : fatal error C1083: Cannot open source file: 'py2.7/Modules/_multiprocessing/multiprocessing.c': No such file or directory
running build

Is there something I am missing? I am using Windows 10, python 2.7.10 (64 bit)

**Comment by mmckerns** [comment]
@ritviksahajpal:  That's weird.  It should be `building '_multiprocess' extension`, where it looks for `Modules/_multiprocess/multiprocess.c` and similar -- not `_multiprocessing`.  Can you say more about how you obtained and tried to build `multiprocess`?

**Comment by ritviksahajpal** [comment]
@mmckerns , here are the steps:

1. I downloaded the code from:http://danse.cacr.caltech.edu/packages/dev_danse_us/multiprocess-0.70.3.zip
2. Unzipped the package
3. On command line did this: python.exe C:\Users\ritvik\Downloads\multiprocess-0.70.1\multiprocess-0.70.1\setup.py build

Python is anaconda 64 bit python 2.7

**Comment by ritviksahajpal** [comment]
![image](https://cloud.githubusercontent.com/assets/2277375/10234954/385dee20-6866-11e5-9001-3a9109485d69.png)

Here is the screenshot

**Comment by mmckerns** [comment]
which python does the `python.exe` belong to?  if you are mixing the `python2.7`'s then this can cause build failure.

**Comment by ritviksahajpal** [comment]
Thanks for looking into this @mmckerns. python.exe belongs to anaconda python 2.7.10 64 bit. 

Unfortunately, I cannot uninstall the other python2.7's since there is a library in each case which depends on that particular python installation

**Comment by mmckerns** [comment]
I'm not looking for you to install another python, I'm trying to rule out reasons that your library is not being found.  The next issue would be that your `PATH` is not set up correctly to find the installed libraries -- have you installed other modules by hand (i.e. with `setup.py`)?  Have those other modules included C code?  By the way, `multiprocess` (and `pathos`) **can** be installed with `pip` or `setuptools`.  See: https://github.com/mmckerns/tuthpc

**Comment by ritviksahajpal** [comment]
@mmckerns , I have installed other modules by hand (setup.py), but none of them with C code (as far as I know). I did check the path to point to where MSVC compiler for python is.

**Comment by mmckerns** [comment]
I mean, the include path and such.  where are you executing (3) from?  It's weird to give the full path for the setup.py file.  Typically, you change to the directory where the setup.py file is, then run `python.exe setup.py build`… reason being, any subfolders that need to be found (ike `Modules/...` in this case) are at the path where they are expected.

**Comment by ritviksahajpal** [comment]
You are right about running python setup.py build from within that folder. I will do that. Not sure what you mean by include path and also by (3) ?

**Comment by mmckerns** [comment]
What I mean by the include path is the `LIBRARY_PATH, and other environment variables.  These are required for compiling and linking code.  If you are running out of the expected folder, you shouldn't need them to be set.  If you aren't, then you probably would.    What I meant by (3) was your step 3 in your build.

**Comment by ritviksahajpal** [comment]
Thanks for the clarification, re (3), I am executing from C:\Anacoda64. Although I could execute elsewhere since python 2.7 64 bit is my default python and is in the windows path. Since it is windows, there is no LIBRARY_PATH (or maybe I am not looking in right place)

**Comment by mmckerns** [comment]
Just in case, here's a reference: http://superuser.com/questions/284342.  If you knew this already, please ignore the link.  What I'm saying is that if you install from source in the directory that the package is unzipped to, then you should not need to set environment variables for packages with C code.  If you want to run setup.py from another directory, then *typically* all bets are off on whether it will work for you in general for any package (for python or C, but especially with C).

**Comment by ritviksahajpal** [comment]
Thanks @mmckerns , I will be trying these steps from scratch on another machine, will be updating in another couple of days.

**Comment by mmckerns** [comment]
@ritviksahajpal: I'm going to close this ticket.  If you do find that there are continuing issues, can you please open up a ticket for `multiprocess` as opposed to `pathos`, as your issues are with `multiprocess`?  If and when you open a `multiprocess` ticket that is a continuation of this one, please just reference this ticket with a link.
