### ISSUE TITLE
Is there a way to make sure all spawned processes die ?

### ISSUE THREAD

**Issue by StevenLOL** [uqfoundation/pathos#74]
I am using Process pool, in one test application, process pool could finish task and release all spawned processes.

However , in another application with similar approach,   I found  the number of processes created is  > than the pool size I used (Pool(nodes=4)), at the end of the task around 20 process live in the system.

```
from pathos.multiprocessing import ProcessingPool as Pool
class ...

self.pool=Pool(nodes=4)
...
...
class methods:
...
self.pool.apipe(self.testDictBug,taskid)

```

Is there a way to make sure all spawned processes die ?

**Comment by mmckerns** [comment]
Could you post code that I could try and confirm that there are more processes created than requested?  Depending on how you created the `Pool`, this could be a bug or a feature.  I say this, as you have created the pool inside a class, which has the potential to spawn multiple `Pool` instances.

But, to answer your question. yes.  There are three levels of shutting down a `Pool`.  Two of them are the same as in `multiprocessing`, and one is unique to `pathos`.
```
>>> from pathos.pools import ProcessPool
>>> p = ProcessPool()
>>> p.map(lambda x:x, range(4))
[0, 1, 2, 3]
>>> # don't allow pool to take any more jobs
>>> p.close()
>>> # shut down all spawned processes
>>> p.join()
>>> # kill the pool and remove it from the pool cache
>>> p.terminate()
>>> # restore pool to a working state
>>> p.restart()
<multiprocess.pool.Pool object at 0x10cd9ead0>
>>> # shut down again...
>>> p.join()
>>> p.close()
>>> p.terminate()
```

**Comment by mmckerns** [comment]
Let me know if the above is what you are looking for.  If you still see more spawned processes than you are requesting from the `Pool`, then please post code demonstrating the behavior.  If not, feel free to close this ticket.

**Comment by StevenLOL** [comment]
Thanks for writing,  that is what I need.
