### ISSUE TITLE
cPickle Issue with Redhat?

### ISSUE THREAD

**Issue by HenryWJReeve** [uqfoundation/pathos#75]
I am trying to set up pathos. I am running into difficulties, despite following the same steps as I followed on a previous successful install on another machine.

Using Anaconda, with pip installed I run:
pip install git+https://github.com/uqfoundation/pathos.git@master

However, when I use Pool from pathos.multiprocessing I get the following error:
“cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed”

Its also clear from the error message that pathos.multiprocessing is falling back on a standard version of multiprocessing. I've seen in other messages that one needs a C compiler installed, but since gcc is installed I definitely have a C compiler installed.

Any help would be very much appreciated.

**Comment by mmckerns** [comment]
If it's failing on `cPickle`, then the issue is likely an issue with building `multiprocess`.  Can you do an install of `multiprocess` (either from the release or from github), and then let me know what you get?  Also check, from an interpreter, whether you can `import multiprocess` or `import _multiprocess`.

**Comment by HenryWJReeve** [comment]
I have installed multiprocess. When I try to import multiprocess I get the following error:
"ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found."

Many thanks.

**Comment by HenryWJReeve** [comment]
I've tried: sudo yum install libc6. 
This gives:
No package libc6 available.
Error: Nothing to do

**Comment by mmckerns** [comment]
That sounds like there is something off with your compiler setup (e.g. like you have multiple compiler versions installed in such a fashion that they aren't playing well with each other). Have you installed your own version of gcc? If so, you might have done it in such a way that it conflicts with the system version of gcc.  A quick google suggests a few issues for this error, such as an old system,  Either way, this doesn't sound like a `pathos` (or `multiprocess`) error, but more of an issue with your configuration interaction with the C/C++ compiler.

**Comment by mmckerns** [comment]
please post here if this warrants reopening

**Comment by gevansBigG** [comment]
Ran into this issue today trying to run a pathos-based python app on a new Amazon Linux image (ami-6df1e514).  Have a working case using an Ubuntu based image.   Tried some reinstalls of packages, made no difference to the outcome.  Pathos works great on my Ubuntu box, was very easy to get working.

working case:
```gevans@ip-XX-X-X-XX:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathos.multiprocessing import ProcessingPool
>>> import dill
>>> class ProcClass(object):
...     def __init__(self):
...         pass
...     def f(self,x):
...         return x*x
...
>>> pc = ProcClass()
>>> pl = ProcessingPool(3)
>>> print pl.map(pc.f, range(10))
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
```

failing case:
```[ec2-user@ip-10-5-7-81 ~]$ python
Python 2.7.12 (default, Sep  1 2016, 22:14:00)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathos.multiprocessing import ProcessingPool
>>> import dill
>>> class ProcClass(object):
...     def __init__(self):
...         pass
...     def f(self,x):
...         return x*x
...
>>> pc = ProcClass()
>>> pl = ProcessingPool(3)
>>> print pl.map(pc.f, range(10))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pathos/multiprocessing.py", line 137, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/usr/local/lib/python2.7/site-packages/multiprocess/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/lib/python2.7/site-packages/multiprocess/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

installing  pathos on the Red Hat system:
```
[ec2-user@ip-10-5-7-81 ~]$ sudo pip install git+https://github.com/uqfoundation/pathos.git@master --upgrade
You are using pip version 6.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/uqfoundation/pathos.git@master
  Cloning https://github.com/uqfoundation/pathos.git (to master) to /tmp/pip-2qHs6R-build
Requirement already up-to-date: ppft>=1.6.4.7 in /usr/local/lib/python2.7/site-packages (from pathos==0.2.2.dev0)
Requirement already up-to-date: dill>=0.2.7.1 in /usr/local/lib/python2.7/site-packages (from pathos==0.2.2.dev0)
Requirement already up-to-date: pox>=0.2.3 in /usr/local/lib/python2.7/site-packages (from pathos==0.2.2.dev0)
Requirement already up-to-date: multiprocess>=0.70.5 in /usr/local/lib/python2.7/site-packages (from pathos==0.2.2.dev0)
```

multiprocess does import ok:
```
[ec2-user@ip-10-5-7-81 ~]$ python
Python 2.7.12 (default, Sep  1 2016, 22:14:00)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocess
>>> multiprocess.__version__
'0.70.5'
```
Tried installing pathos via pip using the default package and supplying the git path, outcome the same.

**Comment by mmckerns** [comment]
@gevansBigG: what happens when you try this:
```
import _multiprocess
_multiprocess.__file__
```

Can you also compare versions of the dependencies for each of your two installs?
