### ISSUE TITLE
map function considerably slower than pythons built-in multiprocessing map

### ISSUE THREAD

**Issue by romeric** [uqfoundation/pathos#79]
I am not sure if this is an issue, but I suppose I will submit nevertheless. I have been porting some code from python's multiprocessing to pathos mainly due to pickling issue. However, it seems that pathos's map function is considerably slower than pythons built-in multiprocessing map. Consider the following simple function:

    def foo(a):
        return 2*a

    In [136]: %timeit python_pool.map(foo,range(100))
    1000 loops, best of 3: 360 µs per loop

    In [137]: %timeit pathos_pool.map(foo,range(100))
    100 loops, best of 3: 8.2 ms per loop

    In [138]: %timeit [foo(i) for i in range(100)]
    100000 loops, best of 3: 9.83 µs per loop

for bigger arrays:

    In [139]: %timeit python_pool.map(foo,range(100000))
    10 loops, best of 3: 23.1 ms per loop

    In [140]: %timeit pathos_pool.map(foo,range(100000))
    1 loops, best of 3: 883 ms per loop
    
For more complicated functions, map performs even worse. Is this expected? I am guessing the serialisation mechanism is different, but this is a huge overhead to pay for. I am using the git version of pathos
 
    pip2 install git+https://github.com/uqfoundation/pathos.git@master

**Comment by mmckerns** [comment]
I think this is to be expected, due to overhead of additional imports and better serialization.

It might be possible to squeeze the time down a bit, with some effort.

Note that you can save some time by using `multiprocess` (the direct fork of `multiprocessing`) instead of `pathos`…

```
In [1]: def foo(x): return 2*x

In [2]: import multiprocessing as mp

In [3]: import multiprocess as ms

In [4]: import pathos.multiprocessing as pa

In [5]: mpp = mp.Pool(8)

In [6]: msp = ms.Pool(8)

In [7]: pap = pa.ProcessingPool(8)

In [8]: %timeit mpp.map(foo, range(100))
1000 loops, best of 3: 579 us per loop

In [9]: %timeit msp.map(foo, range(100))
100 loops, best of 3: 9.32 ms per loop

In [10]: %timeit pap.map(foo, range(100))
100 loops, best of 3: 15.4 ms per loop

In [11]: import dill

In [12]: dill.settings['recurse'] = True

In [13]: %timeit msp.map(foo, range(100))
100 loops, best of 3: 14.2 ms per loop

In [14]: mpp.close()

In [15]: msp.close()

In [16]: pap.close()

In [17]: pap.clear() 
```

And, looking purely at the underlying serialization…

```
In [1]: import pickle

In [2]: def foo(x): return 2*x

In [3]: %timeit pickle.dum
pickle.dump   pickle.dumps  

In [3]: %timeit pickle.loads(pickle.dumps(foo))
10000 loops, best of 3: 23.3 us per loop

In [4]: import dill as pickle

In [5]: %timeit pickle.loads(pickle.dumps(foo))
1000 loops, best of 3: 263 us per loop

In [6]: pickle.settings['recurse'] = True

In [7]: %timeit pickle.loads(pickle.dumps(foo))
1000 loops, best of 3: 401 us per loop 
```

You can see `dill` is slower than `pickle`.  I think it's the cost of better serialization.  I'm also sure that everything in `dill`, `multiprocess`, and `pathos` is not speed optimized.  Feel free to dig and improve if you like.
