### ISSUE TITLE
Error logging

### ISSUE THREAD

**Issue by slavasav** [uqfoundation/pathos#80]
I am running imap on a pool and some processes terminate with an error. Is there an equivalent of multiprocessing "log_to_stderr" way to get error output from all processes?

**Comment by mmckerns** [comment]
Does this work for your purposes?
```
>>> from pathos.helpers import mp
>>> mp.log_to_stderr 
<function log_to_stderr at 0x1098ac488>
```

It's a bit buried in `pathos`, I guess.

**Comment by slavasav** [comment]
Perfect, thanks.
