### ISSUE TITLE
Multiprocess Failing to pickle with pyOpenSSL version 16

### ISSUE THREAD

**Issue by Ralithune** [uqfoundation/pathos#88]
Hello!

I've written a wrapper around Gspread (which is itself a wrapper, I know) and am also using Google-api-python-client to interface with Google Drive for more generic drive operations.

Part of my goals with the wrapper is to set up process monitoring - so that calls to the Google Drive API can timeout or otherwise fail without halting the whole program.  Multiprocess is serving this purpose for me; essentially I'm just using it to monitor the process for 60 seconds and then abandon it if hasn't completed yet.

With pyOpenSSL version 0.13.1 installed, everything works great.

With pyOpenSSL version 16 installed, I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/syscheck", line 7285, in <module>
    grapper_log_system(SYS)
  File "/usr/bin/syscheck", line 7062, in grapper_log_system
    grapper.add_worksheet(spreadsheet, "Validations / MAC List", datalist)
  File "/usr/lib/python2.7/site-packages/grapper-0.1-py2.7.egg/grapper/grapper.py", line 57, in wrapper
    return p.get()
  File "/usr/lib64/python2.7/site-packages/multiprocess/pool.py", line 567, in get
    raise self._value
multiprocess.pool.MaybeEncodingError: Error sending result: '<Worksheet 'Validations / MAC List' id:o689mba>'. Reason: 'PicklingError("Can't pickle <type '_cffi_backend.CDataGCP'>: it's not found as _cffi_backend.CDataGCP",)'
```

I've tested pyOpenSSL versions 0.15.1, 0.15, and 0.14, and they all fail in the same way.

```
[BurnC7 (2016-06-24 11:17:48) grapper]# pip install pyOpenSSL==99999
Collecting pyOpenSSL==99999
  Could not find a version that satisfies the requirement pyOpenSSL==99999 (from versions: 0.6, 0.7, 0.8, 0.9, 0.10, 0.12, 0.13, 0.13.1, 0.14, 0.15, 0.15.1, 16.0.0)
No matching distribution found for pyOpenSSL==99999
```

Is there something we can do about this, or do I need to be posting at pyOpenSSL?

**Comment by mmckerns** [comment]
Sorry this slipped through the cracks somehow and it's taken this long for it to get a reply.

Is this still an issue?  If so, can you post some minimal code that reproduces the error?  Can you reproduce the PicklingError purely from `dill`?  An error of this type from `dill` is common when an object's `__name__ != __qualname__`.  If you can reproduce the error with `dill` (e.g. with no `multiprocess` or `pathos`), then I'd either post this issue with `dill` or OpenSSL, probably the latter.

**Comment by mmckerns** [comment]
If this is still an issue, then please reopen the ticket.
