### ISSUE TITLE
ImportError: No module named pools

### ISSUE THREAD

**Issue by awhillas** [uqfoundation/pathos#91]
installed pathos via pip and from the shell tried:
```
>>> import pathos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pathos.py", line 1, in <module>
    from pathos.pools import ProcessPool as Pool
ImportError: No module named pools
```
python 2.7.11

**Comment by mbelmadani** [comment]
Try this:
`from pathos.multiprocessing import ProcessingPool as Pool`

**Comment by mmckerns** [comment]
I agree with @mbelmadani: the first thing to try is:
```
>>> import pathos
>>> print pathos
<module 'pathos' from '/usr/lib/python2.7/site-packages/pathos-0.2.0.dev0-py2.7.egg/pathos/__init__.pyc'>
```
Then you can check you are importing from the `pathos` you think you are.
I suspect you have a `pathos.py` in your `PYTHONPATH`, and that is being imported instead of the `pathos` package.

If this resolves your issue, please let us know.

**Comment by mmckerns** [comment]
I'm assuming the lack of follow-up means that it's closed.  @awhillas, if it's not resolved for you, reopen the issue.
